export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_SUCCESS = 'API_REQUEST_SUCCESS';
export const API_REQUEST_FAILURE = 'API_REQUEST_FAILURE';
export const API_REQUEST_NETWORK_ERROR = 'API_REQUEST_NETWORK_ERROR';

export const FETCH_TOP_STORY_IDS = 'FETCH_TOP_STORY_IDS';
export const FETCH_TOP_STORY_IDS_SUCCESS = 'FETCH_TOP_STORY_IDS_SUCCESS';
export const FETCH_TOP_STORY_IDS_FAILURE = 'FETCH_TOP_STORY_IDS_FAILURE';

export const FETCH_TOP_STORIES = 'FETCH_TOP_STORIES';
export const FETCH_TOP_STORIES_SUCCESS = 'FETCH_TOP_STORIES_SUCCESS';
export const FETCH_TOP_STORIES_FAILURE = 'FETCH_TOP_STORIES_FAILURE';

export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_NEXT_TOP_STORIES = 'FETCH_NEXT_TOP_STORIES';